---
- hosts: tomcat-jcp
  vars:
     # Remote Destination path on tomcat Nodes.
     remote_dest_path1: /data/tomcat-jcp1

     # Remote Destination path on tomcat Nodes.
     remote_dest_path2: /data/tomcat-jcp2

     # Source Base path where the ansible script is running.
     src_base_path: /root/ansible-playbook/tomcat_playbook

     # Tomcat Install Directory on Destination Tomcat Nodes.
     tomcat_base1: /opt/tomcat-jcp1
     
     # Tomcat Install Directory on Destination Tomcat Nodes.
     tomcat_base2: /opt/tomcat-jcp2

     shutdown_port1: 8005
     shutdown_port2: 8015
      
     http_port1: 8080
     http_port2: 8081
 
     ajp_port1: 8091
     ajp_port2: 8092

  # using `root` user the do all the work.
  remote_user: root

  tasks:

  - name: Create a First Remote Directory to Store our Data.
    file: path={{ remote_dest_path1 }} state=directory

  - name: Create a Second Remote Directory to Store our Data.
    file: path={{ remote_dest_path2 }} state=directory
  
  - name: Copy Archive from ConfMgr to Destination Servers.
    copy: src={{ src_base_path }}/config/apache-tomcat-7.0.59.tar.gz dest={{ remote_dest_path1 }}

  - name: Copy Archive from ConfMgr to Destination Servers.
    copy: src={{ src_base_path }}/config/apache-tomcat-7.0.59.tar.gz dest={{ remote_dest_path2 }}

  # Password Generated using python command below.
  #     python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
  # Current `hdadmin` password is = hdadmin@123

  - name: Create a User `hdadmin`.
    user: name=hdadmin password=$6$rounds=40000$1qjG/hovLZOkcerH$CK4Or3w8rR3KabccowciZZUeD.nIwR/VINUa2uPsmGK/2xnmOt80TjDwbof9rNvnYY6icCkdAR2qrFquirBtT1

  - name: UnArchive the Package in Destination Server.
    unarchive: src={{ remote_dest_path1 }}/apache-tomcat-7.0.59.tar.gz dest={{ remote_dest_path1 }} 

  - name: UnArchive the Package in Destination Server.
    unarchive: src={{ remote_dest_path2 }}/apache-tomcat-7.0.59.tar.gz dest={{ remote_dest_path2 }} 
  
  #- name: Change Directory Permissions.
  #  file: path=/opt/apache-tomcat-7.0.59 owner=hdadmin group=hdadmin recurse=yes

  - name: Creating a Symbolic Link in /opt/tomcat-jcp1.
    file: src={{ remote_dest_path1 }}/apache-tomcat-7.0.59 path={{ tomcat_base1 }} state=link

  - name: Creating a Symbolic Link in /opt/tomcat-jcp2.
    file: src={{ remote_dest_path2 }}/apache-tomcat-7.0.59 path={{ tomcat_base2 }} state=link
  
  - name: Updating Configuration File in Tomcat-Jcp1.
    template: src=config/config-jcp1/server.xml dest={{ tomcat_base1 }}/conf/server.xml

  - name: Updating Configuration File in Tomcat-Jcp2.
    template: src=config/config-jcp2/server.xml dest={{ tomcat_base2 }}/conf/server.xml
  
  - name: Updating JVMParameter Configuration File in Tomcat.
    copy: src=config/config-jcp1/setenv.sh dest={{ tomcat_base1 }}/bin

  - name: Updating JVMParameter Configuration File in Tomcat.
    copy: src=config/config-jcp2/setenv.sh dest={{ tomcat_base2 }}/bin
  
  - name: Change File Permission
    file: path={{ tomcat_base1 }}/bin/setenv.sh mode=0777

  - name: Change File Permission
    file: path={{ tomcat_base2 }}/bin/setenv.sh mode=0777
  
  - name: Configuring Start Script
    copy: src=config/config-jcp1/tomcat-start.sh dest={{ tomcat_base1 }}/bin

  - name: Configuring Start Script
    copy: src=config/config-jcp2/tomcat-start.sh dest={{ tomcat_base2 }}/bin
  
  - name: Change File Permission of Start Script On First Tomcat Server
    file: path={{ tomcat_base1 }}/bin/tomcat-start.sh mode=0777

  - name: Change File Permission of Start Script On Second Tomcat Server
    file: path={{ tomcat_base2 }}/bin/tomcat-start.sh mode=0777
  
  - name: Starting First Tomcat Server
    command: sh {{ tomcat_base1 }}/bin/tomcat-start.sh
  
  - name: Starting Second Tomcat Server
    command: sh {{ tomcat_base2 }}/bin/tomcat-start.sh
    
